# Generated by Django 4.0.5 on 2022-07-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='produts',
            new_name='products',
        ),
    ]
